//! `OrchestrationBackend` — pluggable task scheduling for the `EpiGraph` kernel.
//!
//! The kernel ships with [`NoOpOrchestrationBackend`], which accepts task
//! submissions silently and always reports status as [`TaskStatus::Unknown`].
//! The enterprise layer supplies an implementation backed by a durable task
//! queue (e.g. the `epigraph-orchestrator` crate) that persists tasks,
//! retries on failure, and surfaces real status.
//!
//! # Extension point contract
//!
//! - [`OrchestrationBackend::submit`] is fire-and-forget for the no-op; real
//!   backends must durably enqueue before returning `Ok(())`.
//! - [`OrchestrationBackend::status`] returning [`TaskStatus::Unknown`] is
//!   safe — callers must handle it as "not tracked by this backend."
//! - Task IDs are `Uuid`s generated by the caller before submission, so the
//!   backend does not need to allocate them.

use async_trait::async_trait;
use uuid::Uuid;
use serde_json::Value;

use crate::InterfaceError;

/// Errors returned by [`OrchestrationBackend`] implementations.
#[derive(Debug, thiserror::Error)]
pub enum OrchestrationError {
    /// The task queue is full or temporarily unavailable.
    #[error("task queue unavailable: {0}")]
    QueueUnavailable(String),
    /// The requested task ID was not found in the backend's store.
    #[error("task not found: {task_id}")]
    TaskNotFound { task_id: Uuid },
    /// Any other backend-specific error.
    #[error("orchestration backend error: {0}")]
    Backend(#[from] InterfaceError),
}

/// The lifecycle status of a submitted task.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum TaskStatus {
    /// Task is queued and waiting to be picked up.
    Pending,
    /// Task is currently being executed.
    Running,
    /// Task completed successfully.
    Completed,
    /// Task failed; the backend may retry depending on configuration.
    Failed { reason: String },
    /// Task ID is not known to this backend (no-op default).
    Unknown,
}

/// Pluggable task orchestration backend.
///
/// The kernel holds an `Arc<dyn OrchestrationBackend>` in [`AppState`]. At
/// startup the kernel installs [`NoOpOrchestrationBackend`]; the enterprise
/// layer replaces it with a durable queue implementation.
///
/// [`AppState`]: epigraph_api::state::AppState
#[async_trait]
pub trait OrchestrationBackend: Send + Sync + 'static {
    /// Submit a task with the given `task_id` and JSON `payload`.
    ///
    /// The caller generates `task_id` before submission so that it can track
    /// the task without waiting for the backend to allocate an ID.
    ///
    /// The no-op silently discards the submission.
    async fn submit(
        &self,
        task_id: Uuid,
        payload: Value,
    ) -> Result<(), OrchestrationError>;

    /// Query the current status of a previously submitted task.
    ///
    /// The no-op always returns [`TaskStatus::Unknown`].
    async fn status(&self, task_id: Uuid) -> Result<TaskStatus, OrchestrationError>;

    /// Return `true` if this backend durably persists tasks.
    ///
    /// The kernel uses this to decide whether to write task records to the
    /// DB itself (when the no-op is active) or delegate fully to the backend.
    fn is_active(&self) -> bool;
}

/// Kernel-default no-op orchestration backend.
///
/// Submissions are silently dropped. Status queries always return
/// [`TaskStatus::Unknown`]. `is_active()` returns `false`.
#[derive(Debug, Default, Clone)]
pub struct NoOpOrchestrationBackend;

impl NoOpOrchestrationBackend {
    /// Create a new no-op orchestration backend.
    #[must_use]
    pub const fn new() -> Self {
        Self
    }
}

#[async_trait]
impl OrchestrationBackend for NoOpOrchestrationBackend {
    async fn submit(
        &self,
        _task_id: Uuid,
        _payload: Value,
    ) -> Result<(), OrchestrationError> {
        Ok(())
    }

    async fn status(&self, _task_id: Uuid) -> Result<TaskStatus, OrchestrationError> {
        Ok(TaskStatus::Unknown)
    }

    fn is_active(&self) -> bool {
        false
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn noop_submit_succeeds_silently() {
        let backend = NoOpOrchestrationBackend::new();
        let id = Uuid::new_v4();
        let result = backend.submit(id, serde_json::json!({"step": "test"})).await;
        assert!(result.is_ok());
    }

    #[tokio::test]
    async fn noop_status_is_unknown() {
        let backend = NoOpOrchestrationBackend::new();
        let status = backend.status(Uuid::new_v4()).await.unwrap();
        assert_eq!(status, TaskStatus::Unknown);
    }

    #[test]
    fn noop_is_not_active() {
        assert!(!NoOpOrchestrationBackend::new().is_active());
    }
}
